### ISSUE TITLE
invalid character 'x' looking for beginning of value

### ISSUE THREAD

**Issue by moxcomic** [sirodeneko/gobilibiliDanmu#1]
成功连接到房间后有人发送弹幕就会断开, error提示 invalid character 'x' looking for beginning of value

**Comment by moxcomic** [comment]
有人进入房间似乎也会引起这个错误, 经过调试发现在 `bilibiliclient.go` line 250 处读取到的 messages 为乱码

**Comment by sirodeneko** [comment]
懂了，B站做了二次封包，在数据包里进行了封包 其4~8位是包长

代码已经更新

**Comment by moxcomic** [comment]
测试没啥问题, 能否增加一个发送弹幕的接口呢

**Comment by sirodeneko** [comment]
发送弹幕涉及到登陆会比较麻烦

**Comment by moxcomic** [comment]
或许可以考虑让用户自己扫码登录然后获取cookie之类的，可以参考使用 [lorca](https://github.com/zserge/lorca) 这个库调起 chrome浏览器然后用用 JavaScript 获取登录数据

**Comment by sirodeneko** [comment]
https://www.bilibili.com/read/cv4837223/

这个项目使用的接口只是获取弹幕，B站发送弹幕都是在网页端直接发送，cookie拿到了就可以轻松进行发送。这个并不在本项目范围内
模拟登陆其实没有什么很好的方案（或者说各种方案比较麻烦）让用户手动填写cookie会比较方便

**Comment by moxcomic** [comment]
那就让用户手动填写cookie吧，毕竟发送弹幕还是有需求的
